---
test:
  ibm_power_hmc_defaults: &ibm_power_hmc_defaults
    username: IBM_POWER_HMC_USERNAME
    password: IBM_POWER_HMC_PASSWORD
    hostname: IBM_POWER_HMC_HOSTNAME
    port: IBM_POWER_HMC_PORT
  ibm_power_hmc:
    <<: *ibm_power_hmc_defaults
