---
test:
  ibm_power_hmc_defaults: &ibm_power_hmc_defaults
    ibm_power_hmc_username: IBM_POWER_HMC_USERNAME
    ibm_power_hmc_password: IBM_POWER_HMC_PASSWORD
    ibm_power_hmc_hostname: IBM_POWER_HMC_HOSTNAME
    ibm_power_hmc_port: IBM_POWER_HMC_PORT
  ibm_power_hmc:
    <<: *ibm_power_hmc_defaults
